export const site = {
  name: 'López Márquez Abogados',
  shortName: 'López Márquez',
  url: 'https://lopezmarquezabogados.com',
  description: 'Despacho de abogados en Barcelona especializado en Derecho Laboral, Extranjería y asesoramiento jurídico a empresas.',
  descriptionEn: 'Barcelona law firm advising individuals and businesses on employment law, immigration and related legal matters in Spain.',
  phone: '+34 695 385 198',
  phoneHref: 'tel:+34695385198',
  whatsapp: 'https://wa.me/34695385198',
  email: 'lopezmarquezabogados@gmail.com',
  emailHref: 'mailto:lopezmarquezabogados@gmail.com',
  address: {
    street: 'Carrer dels Madrazo, 6',
    locality: 'Barcelona',
    region: 'Cataluña',
    postalCode: '08006',
    country: 'ES'
  },
  maps: 'https://maps.app.goo.gl/No1F8pQ4VmJxHKhM6?g_st=aw',
  instagram: 'https://www.instagram.com/lopez_marquez_abogados/',
  areas: [
    { title: 'Derecho Laboral', href: '/laboral', kicker: 'Trabajadores · Empresas' },
    { title: 'Extranjería', href: '/extranjeria', kicker: 'Residencia · Nacionalidad' },
    { title: 'Empresas', href: '/empresas', kicker: 'Asesoramiento recurrente' }
  ],
  areasEn: [
    { title: 'Employment', href: '/en/employment', kicker: 'Employees · Companies' },
    { title: 'Immigration', href: '/en/immigration', kicker: 'Residence · Nationality' },
    { title: 'Business', href: '/en/business', kicker: 'Employment advice' }
  ]
} as const;

export const localizedPathMap: Record<string, string> = {
  '/': '/en',
  '/en': '/',
  '/laboral': '/en/employment',
  '/en/employment': '/laboral',
  '/laboral/despidos': '/en/employment-dismissal',
  '/en/employment-dismissal': '/laboral/despidos',
  '/laboral/indemnizacion-despido': '/en/employment-severance',
  '/en/employment-severance': '/laboral/indemnizacion-despido',
  '/laboral/reclamacion-salarios': '/en/employment-salary-claims',
  '/en/employment-salary-claims': '/laboral/reclamacion-salarios',
  '/laboral/accidentes-laborales': '/en/workplace-accidents',
  '/en/workplace-accidents': '/laboral/accidentes-laborales',
  '/extranjeria': '/en/immigration',
  '/en/immigration': '/extranjeria',
  '/extranjeria/arraigo': '/en/immigration/regularisation',
  '/en/immigration/regularisation': '/extranjeria/arraigo',
  '/extranjeria/residencia': '/en/immigration/residency',
  '/en/immigration/residency': '/extranjeria/residencia',
  '/extranjeria/nacionalidad-espanola': '/en/immigration/spanish-nationality',
  '/en/immigration/spanish-nationality': '/extranjeria/nacionalidad-espanola',
  '/extranjeria/reagrupacion-familiar': '/en/immigration/family-reunification',
  '/en/immigration/family-reunification': '/extranjeria/reagrupacion-familiar',
  '/empresas': '/en/business',
  '/en/business': '/empresas',
  '/empresas/asesoramiento-laboral': '/en/business/employment-advice',
  '/empresas/iguala-laboral': '/en/business/retainer',
  '/en/business/retainer': '/empresas/iguala-laboral',
  '/sobre-nosotros': '/en/about',
  '/en/about': '/sobre-nosotros',
  '/preguntas-frecuentes': '/en/faqs',
  '/en/faqs': '/preguntas-frecuentes',
  '/recursos': '/en/resources',
  '/en/resources': '/recursos',
  '/recursos/primeras-horas-despido': '/en/resources/first-hours-after-dismissal',
  '/en/resources/first-hours-after-dismissal': '/recursos/primeras-horas-despido',
  '/recursos/despido-20-dias-habiles': '/en/resources/dismissal-deadline-spain',
  '/en/resources/dismissal-deadline-spain': '/recursos/despido-20-dias-habiles',
  '/recursos/arraigo-dos-anos-2026': '/en/resources/arraigo-two-years-spain',
  '/en/resources/arraigo-two-years-spain': '/recursos/arraigo-dos-anos-2026',
  '/recursos/nacionalidad-espanola-plazos': '/en/resources/spanish-nationality-residence-period',
  '/en/resources/spanish-nationality-residence-period': '/recursos/nacionalidad-espanola-plazos',
  '/actualidad-juridica': '/en/legal-updates',
  '/en/legal-updates': '/actualidad-juridica',
  '/contacto': '/en/contact',
  '/en/contact': '/contacto'
};

export const indexableRoutes = [
  '/recursos/primeras-horas-despido',
  '/actualidad-juridica',
  '/', '/laboral', '/laboral/despidos', '/laboral/indemnizacion-despido', '/laboral/reclamacion-salarios',
  '/laboral/accidentes-laborales', '/laboral/penal-laboral', '/extranjeria', '/extranjeria/arraigo',
  '/extranjeria/nacionalidad-espanola', '/extranjeria/residencia', '/extranjeria/reagrupacion-familiar',
  '/empresas', '/empresas/asesoramiento-laboral', '/empresas/iguala-laboral', '/otras-areas', '/civil', '/penal',
  '/administrativo', '/sobre-nosotros', '/preguntas-frecuentes', '/recursos', '/recursos/despido-20-dias-habiles',
  '/recursos/arraigo-dos-anos-2026', '/recursos/nacionalidad-espanola-plazos', '/contacto',
  '/en', '/en/employment', '/en/employment-dismissal', '/en/employment-severance', '/en/employment-salary-claims',
  '/en/workplace-accidents', '/en/immigration', '/en/immigration/residency', '/en/immigration/regularisation',
  '/en/immigration/spanish-nationality', '/en/immigration/family-reunification', '/en/business',
  '/en/business/retainer', '/en/about', '/en/faqs', '/en/resources', '/en/resources/first-hours-after-dismissal',
  '/en/resources/dismissal-deadline-spain', '/en/resources/arraigo-two-years-spain', '/en/resources/spanish-nationality-residence-period',
  '/en/legal-updates', '/en/contact'
] as const;
